#ifndef WRITABLE_PHYSICAL_MEMORY_DEFINED
#define WRITABLE_PHYSICAL_MEMORY_DEFINED
typedef struct { integer_register r; } WRITABLE_PHYSICAL_MEMORY;
#endif
#ifndef WRITABLE_PHYSICAL_MEMORY_DEFINED
#define WRITABLE_PHYSICAL_MEMORY_DEFINED
typedef struct { integer_register r; } WRITABLE_PHYSICAL_MEMORY;
#endif
